//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace PortalFix.Droid.PereladaOraWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PereladaOraWSSoap", Namespace="http://perelada.com/")]
    public partial class PereladaOraWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback FixGetCategoriesOperationCompleted;
        
        private System.Threading.SendOrPostCallback FixGetIncidentlistOperationCompleted;
        
        private System.Threading.SendOrPostCallback FixGetIncidentOperationCompleted;
        
        private System.Threading.SendOrPostCallback FixSendNewIncidentOperationCompleted;
        
        private System.Threading.SendOrPostCallback FixGetSalespersonsOperationCompleted;
        
        private System.Threading.SendOrPostCallback HrsValidateUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback HrsGetDepartmentsOperationCompleted;
        
        private System.Threading.SendOrPostCallback HrsGetProjectsOperationCompleted;
        
        private System.Threading.SendOrPostCallback HrsGetTasksOperationCompleted;
        
        private System.Threading.SendOrPostCallback HrsGetHoursOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PereladaOraWS() {
            this.Url = "http://dccverp.dtc.grupperalada.com/PereladaWS/PereladaOraWS.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event FixGetCategoriesCompletedEventHandler FixGetCategoriesCompleted;
        
        /// <remarks/>
        public event FixGetIncidentlistCompletedEventHandler FixGetIncidentlistCompleted;
        
        /// <remarks/>
        public event FixGetIncidentCompletedEventHandler FixGetIncidentCompleted;
        
        /// <remarks/>
        public event FixSendNewIncidentCompletedEventHandler FixSendNewIncidentCompleted;
        
        /// <remarks/>
        public event FixGetSalespersonsCompletedEventHandler FixGetSalespersonsCompleted;
        
        /// <remarks/>
        public event HrsValidateUserCompletedEventHandler HrsValidateUserCompleted;
        
        /// <remarks/>
        public event HrsGetDepartmentsCompletedEventHandler HrsGetDepartmentsCompleted;
        
        /// <remarks/>
        public event HrsGetProjectsCompletedEventHandler HrsGetProjectsCompleted;
        
        /// <remarks/>
        public event HrsGetTasksCompletedEventHandler HrsGetTasksCompleted;
        
        /// <remarks/>
        public event HrsGetHoursCompletedEventHandler HrsGetHoursCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://perelada.com/FixGetCategories", RequestNamespace="http://perelada.com/", ResponseNamespace="http://perelada.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet FixGetCategories() {
            object[] results = this.Invoke("FixGetCategories", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void FixGetCategoriesAsync() {
            this.FixGetCategoriesAsync(null);
        }
        
        /// <remarks/>
        public void FixGetCategoriesAsync(object userState) {
            if ((this.FixGetCategoriesOperationCompleted == null)) {
                this.FixGetCategoriesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFixGetCategoriesOperationCompleted);
            }
            this.InvokeAsync("FixGetCategories", new object[0], this.FixGetCategoriesOperationCompleted, userState);
        }
        
        private void OnFixGetCategoriesOperationCompleted(object arg) {
            if ((this.FixGetCategoriesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FixGetCategoriesCompleted(this, new FixGetCategoriesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://perelada.com/FixGetIncidentlist", RequestNamespace="http://perelada.com/", ResponseNamespace="http://perelada.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet FixGetIncidentlist(int actor) {
            object[] results = this.Invoke("FixGetIncidentlist", new object[] {
                        actor});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void FixGetIncidentlistAsync(int actor) {
            this.FixGetIncidentlistAsync(actor, null);
        }
        
        /// <remarks/>
        public void FixGetIncidentlistAsync(int actor, object userState) {
            if ((this.FixGetIncidentlistOperationCompleted == null)) {
                this.FixGetIncidentlistOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFixGetIncidentlistOperationCompleted);
            }
            this.InvokeAsync("FixGetIncidentlist", new object[] {
                        actor}, this.FixGetIncidentlistOperationCompleted, userState);
        }
        
        private void OnFixGetIncidentlistOperationCompleted(object arg) {
            if ((this.FixGetIncidentlistCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FixGetIncidentlistCompleted(this, new FixGetIncidentlistCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://perelada.com/FixGetIncident", RequestNamespace="http://perelada.com/", ResponseNamespace="http://perelada.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet FixGetIncident(int actor, int incident) {
            object[] results = this.Invoke("FixGetIncident", new object[] {
                        actor,
                        incident});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void FixGetIncidentAsync(int actor, int incident) {
            this.FixGetIncidentAsync(actor, incident, null);
        }
        
        /// <remarks/>
        public void FixGetIncidentAsync(int actor, int incident, object userState) {
            if ((this.FixGetIncidentOperationCompleted == null)) {
                this.FixGetIncidentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFixGetIncidentOperationCompleted);
            }
            this.InvokeAsync("FixGetIncident", new object[] {
                        actor,
                        incident}, this.FixGetIncidentOperationCompleted, userState);
        }
        
        private void OnFixGetIncidentOperationCompleted(object arg) {
            if ((this.FixGetIncidentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FixGetIncidentCompleted(this, new FixGetIncidentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://perelada.com/FixSendNewIncident", RequestNamespace="http://perelada.com/", ResponseNamespace="http://perelada.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool FixSendNewIncident(string body) {
            object[] results = this.Invoke("FixSendNewIncident", new object[] {
                        body});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void FixSendNewIncidentAsync(string body) {
            this.FixSendNewIncidentAsync(body, null);
        }
        
        /// <remarks/>
        public void FixSendNewIncidentAsync(string body, object userState) {
            if ((this.FixSendNewIncidentOperationCompleted == null)) {
                this.FixSendNewIncidentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFixSendNewIncidentOperationCompleted);
            }
            this.InvokeAsync("FixSendNewIncident", new object[] {
                        body}, this.FixSendNewIncidentOperationCompleted, userState);
        }
        
        private void OnFixSendNewIncidentOperationCompleted(object arg) {
            if ((this.FixSendNewIncidentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FixSendNewIncidentCompleted(this, new FixSendNewIncidentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://perelada.com/FixGetSalespersons", RequestNamespace="http://perelada.com/", ResponseNamespace="http://perelada.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet FixGetSalespersons() {
            object[] results = this.Invoke("FixGetSalespersons", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void FixGetSalespersonsAsync() {
            this.FixGetSalespersonsAsync(null);
        }
        
        /// <remarks/>
        public void FixGetSalespersonsAsync(object userState) {
            if ((this.FixGetSalespersonsOperationCompleted == null)) {
                this.FixGetSalespersonsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFixGetSalespersonsOperationCompleted);
            }
            this.InvokeAsync("FixGetSalespersons", new object[0], this.FixGetSalespersonsOperationCompleted, userState);
        }
        
        private void OnFixGetSalespersonsOperationCompleted(object arg) {
            if ((this.FixGetSalespersonsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FixGetSalespersonsCompleted(this, new FixGetSalespersonsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://perelada.com/HrsValidateUser", RequestNamespace="http://perelada.com/", ResponseNamespace="http://perelada.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet HrsValidateUser(string user, string pass) {
            object[] results = this.Invoke("HrsValidateUser", new object[] {
                        user,
                        pass});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void HrsValidateUserAsync(string user, string pass) {
            this.HrsValidateUserAsync(user, pass, null);
        }
        
        /// <remarks/>
        public void HrsValidateUserAsync(string user, string pass, object userState) {
            if ((this.HrsValidateUserOperationCompleted == null)) {
                this.HrsValidateUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHrsValidateUserOperationCompleted);
            }
            this.InvokeAsync("HrsValidateUser", new object[] {
                        user,
                        pass}, this.HrsValidateUserOperationCompleted, userState);
        }
        
        private void OnHrsValidateUserOperationCompleted(object arg) {
            if ((this.HrsValidateUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HrsValidateUserCompleted(this, new HrsValidateUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://perelada.com/HrsGetDepartments", RequestNamespace="http://perelada.com/", ResponseNamespace="http://perelada.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet HrsGetDepartments() {
            object[] results = this.Invoke("HrsGetDepartments", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void HrsGetDepartmentsAsync() {
            this.HrsGetDepartmentsAsync(null);
        }
        
        /// <remarks/>
        public void HrsGetDepartmentsAsync(object userState) {
            if ((this.HrsGetDepartmentsOperationCompleted == null)) {
                this.HrsGetDepartmentsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHrsGetDepartmentsOperationCompleted);
            }
            this.InvokeAsync("HrsGetDepartments", new object[0], this.HrsGetDepartmentsOperationCompleted, userState);
        }
        
        private void OnHrsGetDepartmentsOperationCompleted(object arg) {
            if ((this.HrsGetDepartmentsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HrsGetDepartmentsCompleted(this, new HrsGetDepartmentsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://perelada.com/HrsGetProjects", RequestNamespace="http://perelada.com/", ResponseNamespace="http://perelada.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet HrsGetProjects() {
            object[] results = this.Invoke("HrsGetProjects", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void HrsGetProjectsAsync() {
            this.HrsGetProjectsAsync(null);
        }
        
        /// <remarks/>
        public void HrsGetProjectsAsync(object userState) {
            if ((this.HrsGetProjectsOperationCompleted == null)) {
                this.HrsGetProjectsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHrsGetProjectsOperationCompleted);
            }
            this.InvokeAsync("HrsGetProjects", new object[0], this.HrsGetProjectsOperationCompleted, userState);
        }
        
        private void OnHrsGetProjectsOperationCompleted(object arg) {
            if ((this.HrsGetProjectsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HrsGetProjectsCompleted(this, new HrsGetProjectsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://perelada.com/HrsGetTasks", RequestNamespace="http://perelada.com/", ResponseNamespace="http://perelada.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet HrsGetTasks(string project) {
            object[] results = this.Invoke("HrsGetTasks", new object[] {
                        project});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void HrsGetTasksAsync(string project) {
            this.HrsGetTasksAsync(project, null);
        }
        
        /// <remarks/>
        public void HrsGetTasksAsync(string project, object userState) {
            if ((this.HrsGetTasksOperationCompleted == null)) {
                this.HrsGetTasksOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHrsGetTasksOperationCompleted);
            }
            this.InvokeAsync("HrsGetTasks", new object[] {
                        project}, this.HrsGetTasksOperationCompleted, userState);
        }
        
        private void OnHrsGetTasksOperationCompleted(object arg) {
            if ((this.HrsGetTasksCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HrsGetTasksCompleted(this, new HrsGetTasksCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://perelada.com/HrsGetHours", RequestNamespace="http://perelada.com/", ResponseNamespace="http://perelada.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet HrsGetHours(string user, string project) {
            object[] results = this.Invoke("HrsGetHours", new object[] {
                        user,
                        project});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void HrsGetHoursAsync(string user, string project) {
            this.HrsGetHoursAsync(user, project, null);
        }
        
        /// <remarks/>
        public void HrsGetHoursAsync(string user, string project, object userState) {
            if ((this.HrsGetHoursOperationCompleted == null)) {
                this.HrsGetHoursOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHrsGetHoursOperationCompleted);
            }
            this.InvokeAsync("HrsGetHours", new object[] {
                        user,
                        project}, this.HrsGetHoursOperationCompleted, userState);
        }
        
        private void OnHrsGetHoursOperationCompleted(object arg) {
            if ((this.HrsGetHoursCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HrsGetHoursCompleted(this, new HrsGetHoursCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void FixGetCategoriesCompletedEventHandler(object sender, FixGetCategoriesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FixGetCategoriesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FixGetCategoriesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void FixGetIncidentlistCompletedEventHandler(object sender, FixGetIncidentlistCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FixGetIncidentlistCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FixGetIncidentlistCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void FixGetIncidentCompletedEventHandler(object sender, FixGetIncidentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FixGetIncidentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FixGetIncidentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void FixSendNewIncidentCompletedEventHandler(object sender, FixSendNewIncidentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FixSendNewIncidentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FixSendNewIncidentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void FixGetSalespersonsCompletedEventHandler(object sender, FixGetSalespersonsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FixGetSalespersonsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FixGetSalespersonsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void HrsValidateUserCompletedEventHandler(object sender, HrsValidateUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HrsValidateUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HrsValidateUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void HrsGetDepartmentsCompletedEventHandler(object sender, HrsGetDepartmentsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HrsGetDepartmentsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HrsGetDepartmentsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void HrsGetProjectsCompletedEventHandler(object sender, HrsGetProjectsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HrsGetProjectsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HrsGetProjectsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void HrsGetTasksCompletedEventHandler(object sender, HrsGetTasksCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HrsGetTasksCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HrsGetTasksCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void HrsGetHoursCompletedEventHandler(object sender, HrsGetHoursCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HrsGetHoursCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HrsGetHoursCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591